# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: danyal-XPS-15-9500
    steps:
    - uses: actions/checkout@v3
    - run: cd ~/e2e-exchange-testing
    - run: yarn test_local
