# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e testing

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    runs-on: self-hosted
    steps:
      # - uses: AutoModality/action-clean@v1  DSFDSF
      - uses: actions/checkout@v3
      - name: create .env
        run: |
          echo MY_SECRET="$MY_SECRET" > .env
          echo PAIR_NAME="$MY_SECRET" >> .env
          echo PAIR_NAME1=${{ secrets.MY_SECRET }} >> .env
          echo PAIR_NAME2="${{ secrets.MY_SECRET }}" >> .env
      - name: run index.js
        run: node index.js
      - name: start testing
        run: cd ~/e2e-exchange-testing && pwd && yarn skip_testing
